M-10 Stworzenie serwisu http
jankes1006/webapp-microservices pull request #1
Opened 2022-12-03 10:52 UTC by jankes1006

Stworzenie serwisu Http. Odpowiada on za komunikacje za pomocą http (przygotowuje odpowiednio heder). W ramach zadania przygotowano serwis do autoryzacji.

2022-12-03 11:17 UTC, jrubach commented on src/app/core/auth-service/auth.service.ts
> +  login(username: string, password: string): void {
dodaj zabezpieczenie przed nullami

2022-12-03 11:19 UTC, jrubach requested changes

2022-12-03 11:19 UTC, jrubach commented on src/app/core/dto/auth-dto.ts
> +export interface AuthDto{
jw

2022-12-03 11:19 UTC, jrubach commented on src/app/core/dto/login-user-dto.ts
> +export interface LoginUserDto {
jw

2022-12-09 19:13 UTC, jankes1006 commented on src/app/core/dto/auth-dto.ts
> +export interface AuthDto{
Poprawiono

2022-12-09 19:14 UTC, jankes1006 commented on src/app/core/dto/login-user-dto.ts
> +export interface LoginUserDto {
Poprawiono.

2022-12-11 18:24 UTC, jrubach approved these changes

2022-12-11 18:25 UTC, merged